### ISSUE TITLE
Compiling App gets stuck if LLVM is enabled

### ISSUE THREAD

**Issue by Cheesebaron** [markuspalme/LottieNet6#1]
As title says, publishing a release version of an App using this library, makes LLVM get stuck.

**Comment by markuspalme** [comment]
Do you use this library in a `net6-ios`project or in a Xamarin project? Can you please share the command line you use for publishing the release version?

Thanks!

**Comment by Cheesebaron** [comment]
net6.0-ios

I stopped caring much about this project and moved on to use Skottie instead.

Do what you want with the information.

**Comment by markuspalme** [comment]
Thanks for the update. I built the demo application using this command which should enable LLVM and the build completed without any problems:

```dotnet build /p:MtouchUseLlvm=true --runtime ios-arm64  --self-contained --configuration Release```

**Comment by Cheesebaron** [comment]
Perhaps at the time I had the issue there was a general issue with the tooling 🤷‍♂️
