### ISSUE TITLE
Possible Issue on the AppStore

### ISSUE THREAD

**Issue by fdhsdrdark** [markuspalme/LottieNet6#2]
Hey, 
Thank you very much for this puget package!
It seemed the only way to continue using Lottie animations on my migrated to .Net 6 app.
I run into an issue though and I'm not really sure If this package is related in any way.
When I uploaded my app on the App Store I got an email about the app being rejected, with the following
"The app references non-public symbols in MyAppName: _ubrk_openRules, _ucal_add, _ucal_close, _ucal_get, _ucal_getAttribute, _ucal_getKeywordValuesForLocale, _ucal_getNow, _ucal_getTimeZoneDisplayName, _ucal_getTimeZoneIDForWindowsID, _ucal_getWindowsTimeZoneID".

Googled for _ucal_getWindowsTimeZoneID and Cylinder came up(never used it). 
Since Cylinder is related to animations I suspected Lottie.iOS package might have something to do with the error.

Is there any change the error is from Lottie.iOS package? 
Thanks vey much for any response.

**Comment by markuspalme** [comment]
The mentioned symbols are related to `libicucore`, a system library providing Unicode and localization support.

I could not find a reference to this library in this project or in the native Lottie library. 

I think you need to audit your dependencies to find out where the reference is coming from.

**Comment by fdhsdrdark** [comment]
Thank you very much for getting back so quickly and also for the detailed response. I really appreciate it.
I will check the rest package references.
